# Generated by Django 2.0.5 on 2018-06-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('MAU', models.IntegerField(default=0)),
                ('DAU', models.IntegerField(default=0)),
                ('industry_percent', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('income_rate', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('business', models.CharField(default='未知', max_length=30)),
                ('architect', models.CharField(default='未知', max_length=30)),
                ('died_cause', models.TextField(default='未知')),
                ('isCommend', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSecType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='itemsectype',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemSecType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemSecType'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemType'),
        ),
    ]
