# Generated by Django 2.0.5 on 2018-06-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='DAU',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='MAU',
            field=models.FloatField(default=0),
        ),
    ]
