# Generated by Django 2.0.5 on 2018-06-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('market_value', models.IntegerField(default=0)),
                ('upCloud', models.CharField(default='未知', max_length=20)),
                ('upCloud_percent', models.IntegerField(default=0)),
                ('upCloud_time', models.DateTimeField(default=None)),
                ('invest', models.CharField(default='未知', max_length=20)),
                ('income', models.IntegerField(default=0)),
                ('income_increase_rate', models.IntegerField(default=0)),
                ('attribute', models.IntegerField(default=0)),
                ('location', models.CharField(default='未知', max_length=10)),
                ('contacter', models.CharField(default='未知', max_length=10)),
                ('contact_phone', models.CharField(default='未知', max_length=11)),
            ],
        ),
    ]
