# Generated by Django 2.0.5 on 2018-06-03 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='upCloud_time',
            field=models.DateTimeField(default=datetime.datetime(1111, 11, 11, 0, 0)),
        ),
    ]
